export const words = {
  FamousPeople: [
    "ahmed helmy",
    "mohamed salah",
    "amr diab",
    "naguib mahfouz",
    "taha hussien",
    "messi",
    "cristiano",
    "ahmed Zewail",
    "mostafa rayan",
  ],
  movies: [
    "Me Before You",
    "Inception",
    "Interstellar",
    "Fast Farious",
    "Cast Away",
    "Coco",
    "Up",
  ],
  Elsa7aba: [
    "Omar ebn AlKhattab",
    "Osman ebn Affan",
    "Musab ebn Umair",
    "Ali ebn Abi Talib",
    "Saad ebn Moaz",
    "Talha ebn Ubaidullah",
    "Khalid ebn alWalid",
    "Hamza",
    "AlZubayr ebn alAwwam",
    "Abdulrahman ebn Awf",
    "Saeed ebn Zaid",
    "Saad ebn Abi Waqqas",
  ],
  countries: [
    "Syria",
    "Palestine",
    "Yemen",
    "Egypt",
    "Iraq",
    "Qatar",
    "sudan",
    "saudi arabia",
    "spain",
    "Holland",
    "america",
    "brazil",
    "argentina",
    "england",
    "france",
  ],
};
